// Strapi attribute types
export type FieldType =
  | 'string'
  | 'text'
  | 'richtext'
  | 'email'
  | 'password'
  | 'integer'
  | 'float'
  | 'decimal'
  | 'biginteger'
  | 'number'
  | 'date'
  | 'datetime'
  | 'media'
  | 'json'
  | 'boolean'
  | 'enumeration'
  | 'uid'
  | 'dynamiczone'
