name: on-pr-main

on:
  pull_request:
    branches:
      - main

jobs:
  check-label:
    uses: victorigualada/actions/.github/workflows/block-if-label.yaml@main
    with:
      label: "bug"

  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    secrets: inherit
