name: on-pr-main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
      - edited

jobs:
  check-label:
    uses: victorigualada/actions/.github/workflows/check-required-changes.yaml@main
    with:
      pr_description: ${{ github.event.pull_request.body }}
    secrets: inherit

#  build-lint-test:
#    needs: check-label
#    uses: ./.github/workflows/build-lint-test.yml
#    secrets: inherit
