name: on-pr-main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    secrets: inherit
